version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - rgisler
  ignore:
  - dependency-name: org.openjfx:javafx-fxml
    versions:
    - "17"
  - dependency-name: org.openjfx:javafx-controls
    versions:
    - "17"
